"""empty message

Revision ID: 17a21c5d7e68
Revises: daaeb1536a9f
Create Date: 2021-03-04 08:39:02.268124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17a21c5d7e68'
down_revision = 'daaeb1536a9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=False))
    op.drop_index('user_name', table_name='users')
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'user_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_name', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('user_name', 'users', ['user_name'], unique=True)
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
