"""empty message

Revision ID: 61a1f2177524
Revises: b07769c35a72
Create Date: 2021-02-27 17:58:28.523570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61a1f2177524'
down_revision = 'b07769c35a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('image_use', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machines', 'image_use')
    # ### end Alembic commands ###
