"""empty message

Revision ID: a30c9fc3949b
Revises: 032e6f06210a
Create Date: 2021-02-03 09:19:45.426426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a30c9fc3949b'
down_revision = '032e6f06210a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('machines', sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('muscles', sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('muscles', 'created_date')
    op.drop_column('machines', 'created_date')
    op.drop_column('exercises', 'created_date')
    # ### end Alembic commands ###
