"""empty message

Revision ID: b07769c35a72
Revises: 7c7ada8f5308
Create Date: 2021-02-24 13:26:58.211626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b07769c35a72'
down_revision = '7c7ada8f5308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines_exercises',
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('machine_id', 'exercise_id')
    )
    op.add_column('machines', sa.Column('image', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machines', 'image')
    op.drop_table('machines_exercises')
    # ### end Alembic commands ###
